version: '3.9'

services:
  standup-saboteur-backend:
    build: .
    container_name: standup-saboteur-backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data   # persist sqlite file
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=file:/app/data/standup-saboteur.db
